#!/usr/bin/env python3
"""Verify FileOrganizer's reproducible Python dependency lock.

The shipped lock targets the supported Windows x64 Python 3.10 baseline. The
same command can be run on newer Python versions; environment markers in the
lock decide which compatible distributions are selected.
"""

from __future__ import annotations

import argparse
import difflib
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent
DEFAULT_MANIFEST = REPO_ROOT / "requirements.txt"
DEFAULT_LOCK = REPO_ROOT / "requirements.lock"
LOCK_PYTHON_VERSION = "3.10"
LOCK_PYTHON_PLATFORM = "x86_64-pc-windows-msvc"


def _tool(name: str) -> str:
    path = shutil.which(name)
    if not path:
        raise RuntimeError(
            f"{name} is required for dependency verification; "
            "install it from the documented setup instructions"
        )
    return path


def _compile_command(manifest: Path, output: Path) -> list[str]:
    return [
        _tool("uv"),
        "pip",
        "compile",
        "--quiet",
        "--generate-hashes",
        "--python-version",
        LOCK_PYTHON_VERSION,
        "--python-platform",
        LOCK_PYTHON_PLATFORM,
        "--output-file",
        str(output),
        str(manifest),
    ]


def _run(command: list[str]) -> None:
    result = subprocess.run(command, cwd=REPO_ROOT, text=True)
    if result.returncode:
        raise RuntimeError(f"Command failed ({result.returncode}): {' '.join(command)}")


def _without_generated_header(path: Path) -> str:
    lines = path.read_text(encoding="utf-8").splitlines()
    while lines and (
        lines[0].startswith("# This file was autogenerated")
        or lines[0].startswith("#    uv pip compile")
    ):
        lines.pop(0)
    return "\n".join(lines).rstrip() + "\n"


def check_lock(manifest: Path, lock: Path) -> None:
    if not lock.is_file():
        raise RuntimeError(f"Missing dependency lock: {lock}")

    with tempfile.TemporaryDirectory(prefix="fileorganizer-lock-") as temp_dir:
        generated = Path(temp_dir) / "requirements.lock"
        _run(_compile_command(manifest, generated))
        expected = _without_generated_header(lock)
        actual = _without_generated_header(generated)
        if expected != actual:
            diff = list(
                difflib.unified_diff(
                    expected.splitlines(),
                    actual.splitlines(),
                    fromfile=str(lock),
                    tofile="fresh uv resolution",
                    lineterm="",
                )
            )
            preview = "\n".join(diff[:80])
            raise RuntimeError(
                "requirements.lock is out of date; regenerate it with the "
                "uv pip compile command from README.md.\n" + preview
            )
    print(f"Lock matches {manifest.name}: {lock.name}")


def validate_lock(lock: Path) -> None:
    _run(
        [
            _tool("uv"),
            "pip",
            "install",
            "--dry-run",
            "--require-hashes",
            "--system",
            "-r",
            str(lock),
        ]
    )
    print(f"Hash-verified resolution is installable: {lock.name}")


def audit_lock(lock: Path) -> None:
    _run([_tool("pip-audit"), "-r", str(lock), "--strict"])
    print(f"Dependency vulnerability audit passed: {lock.name}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--lock", type=Path, default=DEFAULT_LOCK)
    parser.add_argument("--check", action="store_true", help="check lock freshness")
    parser.add_argument("--validate", action="store_true", help="validate hashes and markers")
    parser.add_argument("--audit", action="store_true", help="run pip-audit against the lock")
    args = parser.parse_args(argv)

    if not any((args.check, args.validate, args.audit)):
        parser.error("select at least one of --check, --validate, or --audit")

    try:
        if args.check:
            check_lock(args.manifest.resolve(), args.lock.resolve())
        if args.validate:
            validate_lock(args.lock.resolve())
        if args.audit:
            audit_lock(args.lock.resolve())
    except (OSError, RuntimeError) as exc:
        print(f"Dependency verification failed: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
